config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :punchin
  resources :clients

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/punchin.rb
class Punchin < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	def index
		@client = Client.all
	end

	def show
		@client = Client.find(params[:id])
	end

	def new
	end

	def list_of_client_names
		@client_array = [client.client_name.each]
	end

	def create
		@client = Client.new(client_params)

		@client.save
		redirect_to @client
	end

	private
		def client_params
			params.require(:client).permit(:client_name, :client_rate)
		end

end

app/controllers/punchin_controller.rb
class PunchinController < ApplicationController
	
	def index
		@punchin = Punchin.all
	end

	def show
		@punchin = Punchin.find(params[:id])
	end

	def new
		@punchin = Punchin.new

		@punchin_list = Punchin.select("working").last(1)

		if @punching_list.try :nonzero?
			@asdf = "You are currently clocked in"
		else
			@asdf = "You are currently clocked OUT"
		end

		@list_of_clients = Client.select("DISTINCT client_name").where.not('client_name' => nil).to_a
	end

	def edit
		@punchin = Punchin.find(params[:id])
		@list_of_clients = Client.select("DISTINCT client_name").where.not('client_name' => nil).to_a
	end

	def create
		@punchin = Punchin.new(punchin_params)

		@punchin.save
		redirect_to @punchin
	end

	def update
		@punchin = Punchin.find(params[:id])

		if @punchin.update(punchin_params)
			redirect_to @punchin
		else
			render 'edit'
		end
	end

	def destroy
		@punchin = Punchin.find(params[:id])
		@punchin.destroy

		redirect_to punchin_index_path
	end

	private
		def punchin_params
			params.require(:punchin).permit(:client, :time)
		end

		def in_or_out
			puts "Testing"
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/punchin_helper.rb
module PunchinHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clients/index.html.erb
<h1>Client list</h1>

<%= link_to 'Home', root_path %><br>
<%= link_to 'New client', new_client_path %>

<table>
	<tr>
		<th>Client</th>
		<th>Rate</th>
	</tr>

<% @client.each do |client| %>
	<tr>
		<td><%= client.client_name %></td>
		<td><%= client.client_rate %></td>
	</tr>
<% end %>

</table>
<table>
	<tr>
		<th><%= @client_array %></th>
	</tr>
</table>

app/views/clients/new.html.erb
<h1>Let's add a new client!</h1>

<%= form_for :client, url: clients_path do |f| %>

<p>
	<%= f.label :client_name %><br>
	<%= f.text_area :client_name %>
</p>

<p>
	<%= f.label :client_rate %><br>
	<%= f.text_area :client_rate %>
</p>

<p>
	<%= f.submit %>
</p>

<% end %>

<%= link_to 'Back', clients_path%>

app/views/clients/show.html.erb
<p>
	<strong>Client:</strong>
	<%= @client.client_name %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timeclock</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/punchin/_form.html.erb
<p>Client name</p>
<%= form_for :punchin, url: punchin_index_path do |f| %>
  <%= f.select(:client) do %>
    <% @list_of_clients.each do |c| -%>
      <%= content_tag(:option, c.client_name, value: c.client_name) %>
    <% end %>
  <% end %>

<p>Clocking in?</p>
  <%= f.select(:working) do %>
  <% end %>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/punchin/edit.html.erb
<h1>Edit punchin</h1>
<!--
<%= form_for(@punchin) do |f| %>
	<p>
		<%= f.select(:client) do %>
    	<% [['Lauren'], ['Mariah']].each do |c| -%>
      	<%= content_tag(:option, c.first, value: c.first) %>
    	<% end %>
  	<% end %>
	</p>
-->

<%= render 'form' %>

<% end %>

<%= link_to 'Back', punchin_index_path %>

app/views/punchin/index.html.erb
<h1>Punches</h1>

<%= link_to 'Home', root_path %><br>
<%= link_to 'New punch in', new_punchin_path %><br>

<%= @first_punch %>

<table>
	<tr>
		<th>Client</th>
		<th>Time</th>
		<th>Working?</th>
	</tr>

	<% @punchin.each do |punchin| %>
		<tr>
			<td><%= punchin.client %></td>
			<!--<td><%= punchin.time %></td>-->
			<td><%= punchin.created_at.in_time_zone("Pacific Time (US & Canada)") %></td>
			<td><%= punchin.working %></td>
			<td><%= link_to 'Show', punchin_path(punchin) %></td>
			<td><%= link_to 'Edit', edit_punchin_path(punchin) %></td>
			<td><%= link_to 'Destroy', punchin_path(punchin),
					method: :delete,
					data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
</table>

app/views/punchin/new.html.erb
<h1> Punch in or Punch out </h1>

<%= render 'form' %>

<%= link_to 'Back', punchin_index_path %>

<% @punchin_list.each do |punchin| %>
	<tr>
		<td><%= punchin.working %></td>
	</tr>
<% end %>

<%= @asdf %>

app/views/punchin/show.html.erb
<p>
	<strong>Client:</strong>
	<%= @punchin.client %>
</p>

<p>
	<strong>Time:</strong>
	<%= @punchin.created_at.in_time_zone("Pacific Time (US & Canada)") %>
</p>

<%= link_to 'Back', punchin_index_path %>

app/views/welcome/index.html.erb
<h1>Table of contents</h1>
<%= link_to 'Punches', controller: 'punchin' %><br>
<%= link_to 'Clients', controller: 'clients' %>